<h1>PROBLEM 1: EDIT DISTANCE <h1>

In [1]:
def find_minimum_edit_distance(source_string, target_string):

    # Create a dp matrix of dimension (source_string +1)  x (destination_matrix +1)
    dp = [[0]* (len(source_string)+1) for i in range(len(target_string)+1)]

    # Initialize the required values of the matrix

    for i in range(1, len(target_string)+1):
        dp[i][0] = dp[i-1][0] +1
    for i in range(1, len(source_string)+1):
        dp[0][i] = dp[0][i-1] +1

    # Maintain the record of operations done
    #Record is one tuple. EG : (Insert, 'a') or (SUBSTITURE, 'a', 'b')

    operations_performed = []


    #build the matrix following the algorithm

    for i in range(1, len(target_string)+1):
        for j in range(1, len(source_string)+1):
            if source_string[j-1] == target_string[i-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = 1 + min(dp[i-1][j]+ 1 ,
                                   dp[i-1][j-1]+2,
                                   dp[i][j-1] +1)

    # Initialize for backtracking
    i = len(target_string)
    j = len(source_string)

    # Backtrack to record the operation performed
    while (i != 0 and j != 0):
        # IF the charater of the source string is equal to 
        # the character of ther destination string,
        # no operation is performed

        if target_string[i-1] == source_string[j-1]:
            i -= 1
            j -= 1
        else:
            #check if the current element is derrived from the upper-left diagonal element
            if dp[i][j] == dp[i-1][j-1] + 2:
                operations_performed.append(('SUBSTITUTE',source_string[j-1],target_string[i-1]))
                i -= 1
                j -= 1
            else :
                # check if the current element if derived from the upper-left diagnal element
                if dp[i][j] == dp[i-1][j] + 1:
                    operations_performed.append(('DELETE', source_string[j-1]))
                    i -= 1
                else:
                    operations_performed.append(('INSERT', target_string[i-1]))
                    if dp[i][j] == dp[i-1][j-1] + 2:
                        operations_performed.append(('SUBSTITUTE', source_string[j-1], target_string[i-1]))
                        i -= 1
                        j -= 1
                    elif dp[i][j] == dp[i-1][j] +1:
                        operations_performed.append(('INSERT',target_string[i-1]))
                        i -= 1
                    else:
                        operations_performed.append(('DELETE',source_string[j-1]))
                        j -= 1                       



    #if we reach top most row of the matrix

    while (j != 0):
        operations_performed.append(('DELETE', source_string[j-1]))
        j -= 1
    while (i != 0):
        operations_performed.append(('INSERT', target_string[i-1]))
        i -= 1
    # reverse the operations performed
    operations_performed.reverse()
    # return the matrix and the operations performed
    return dp[len(target_string)][len(source_string)], operations_performed
# Test the function
if __name__ == "__main__":
    print("Enter the source string:")
    source_string = input().strip()
    print("Enter the target string:")
    target_string = input().strip()
    # Call the function
    distance, operations_performed = find_minimum_edit_distance(source_string, target_string)
    
    insertions = 0
    deletions = 0
    substitutions = 0
    for i in operations_performed:
        if i[0] == 'INSERT':
            insertions += 1
        elif i[0] == 'DELETE':
            deletions += 1
        elif i[0] == 'SUBSTITUTE':
            substitutions += 1
    print("Minimum edit distance: {}".format(distance) )
    print("number of insertions: {}".format(insertions))
    print("number of deletions: {}".format(deletions))
    print("number of substitutions: {}".format(substitutions))
    print("Total of number of operatios : {}".format(insertions + deletions + substitutions))
    
    print("actual OPeration : ")
    for i in range(len(operations_performed)):
        if operations_performed[i][0] == 'INSERT':
            print("{}) {} : {}".format(i+1,operations_performed[i][0], operations_performed[i][1]))
        elif operations_performed[i][0] == 'DELETE':
            print("{}) {} : {}".format(i+1,operations_performed[i][0], operations_performed[i][1]))
        else :
            print("{}) {} : {} -> {}".format(i+1,operations_performed[i][0], operations_performed[i][1], operations_performed[i][2]))
    print("The operations are performed in the order of the source string")
    

Enter the source string:
Enter the target string:
Minimum edit distance: 2
number of insertions: 0
number of deletions: 2
number of substitutions: 0
Total of number of operatios : 2
actual OPeration : 
1) DELETE : h
2) DELETE : a
The operations are performed in the order of the source string


<h1>PROBLEM 2: LONGEST COMMON SUBSEQUENCE <h1>

In [15]:
def find_LCS(source_string, target_string):

    # Create a dp matrix of dimension (source_string +1)  x (destination_matrix +1)
    dp = [[0]* (len(source_string)+1) for i in range(len(target_string)+1)]

    # Initialize the required values of the matrix

    for i in range(1, len(target_string)+1):
        dp[i][0] = 1
    for i in range(1, len(source_string)+1):
        dp[0][i] = 1

    # Maintain the record of operations done
    #Record is one tuple. EG : (Insert, 'a') or (SUBSTITURE, 'a', 'b')

    common_str = []


    #build the matrix following the algorithm

    for i in range(1, len(target_string)+1):
        for j in range(1, len(source_string)+1):
            if source_string[j-1] == target_string[i-1]:
                dp[i][j] = dp[i-1][j-1]+1
            else:
                dp[i][j] = max(dp[i-1][j],
                                   dp[i-1][j-1],
                                   dp[i][j-1])

    # Initialize for backtracking
    i = len(target_string)
    j = len(source_string)

    # Backtrack to record the operation performed
    while (i != 0 and j != 0):
        # IF the charater of the source string is equal to 
        # the character of ther destination string,
        # add it to the commonn string list

        if target_string[i-1] == source_string[j-1]:
            i -= 1
            j -= 1
            common_str.append(target_string[i])        
        else:
            #if both of the elements is not equal, find the direction in which in derived from.
            directions = [(-1,-1),(-1,0),(0,-1)]
            for direction in directions:
                #Look for the direction in which the current element is derived from
                x = i + direction[0]
                y = j + direction[1]

                #out of bounds
                if x < 0 or y < 0:
                    break

                
                if x >= 0 and y >= 0 and dp[i][j] == dp[x][y]:
                    i = x
                    j = y
                    break
                       
    # reverse the operations performed
    common_str.reverse()
    # return the matrix and the operations performed
    return dp[len(target_string)][len(source_string)]-1, common_str
# Test the function
if __name__ == "__main__":
    print("Enter the source string:")
    source_string = input().strip()
    print("Enter the target string:")
    target_string = input().strip()
    # Call the function
    distance, common_str = find_LCS(source_string, target_string)
    
    print("source string : {}".format(source_string))
    print("target string : {}".format(target_string))
    print("Longest Common Subsequence: {}".format(distance) )
    print("Common Subsequence: {}".format(''.join(common_str) ))

Enter the source string:
Enter the target string:
source string : healo
target string : helllo
Longest Common Subsequence: 3
Common Subsequence: helo


<h1>PROBLEM 3: DYNAMIC TIME WRAPING<h1>

In [24]:
import numpy as np

def find_DTW(source_string, target_string):

    #padding the sequences in order to deal with the edge cases
    source_string = [0] + source_string
    target_string = [0] + target_string

    # assume the target is smaller than the source
    if len(source_string) < len(target_string):
        source_string, target_string = target_string, source_string

    # Create a dp matrix of dimension (source_string +1)  x (destination_matrix +1)
    dwt_table = [[0]* (len(source_string)) for i in range(len(target_string))]

    # Initialize the required values of the matrix
    for i in range(0, len(target_string)):
        dwt_table[i][0] = 0
    for i in range(0, len(source_string)):
        dwt_table[0][i] = 0

    #build the matrix following the algorithm
    for k in range(1, min(len(target_string), len(source_string))):
        #calculate all the DWT[i][k]
        for i in range(1, len(source_string)):
            distance = abs(source_string[i] - target_string[k]) + min (dwt_table[i-1][k-1], 
                                                                           dwt_table[i][k-1], 
                                                                           dwt_table[i-1][k])
            dwt_table[i][k] = distance
        #calculate all the DWT[k][i]
        for i in range(1, len(target_string)):
            distance = abs(source_string[k] - target_string[i]) + min (dwt_table[k-1][i-1], 
                                                                           dwt_table[k][i-1], 
                                                                           dwt_table[k-1][i])
            dwt_table[k][i] = distance

    # Initialize for backtracking
    i = len(target_string)-1
    j = len(source_string)-1
    instructions = []

    # Backtrack to record the operation performed
    while (i != 0 and j != 0):
        # find which direction the current element is derived from
        directions =  [(-1,-1),(-1,0),(0,-1)]
        signs = ["upper left diagonal", "upper", "left"]
        coordinates = [(i+direction[0], j+direction[1]) for direction in directions ]
        where_to_go = np.argmin([dwt_table[coordinate[0]][coordinate[1]] for coordinate in coordinates])
        instructions.append((signs[where_to_go],dwt_table[i][j]))
        i = coordinates[where_to_go][0]
        j = coordinates[where_to_go][1]
    # reverse the operations performed
    instructions.reverse()
    # return the matrix and the operations performed
    return dwt_table, instructions
# Test the functi
if __name__ == "__main__":
    print("Enter the source sequence:")
    source_string = [int(i) for i in input().strip().split()]
    print("Enter the target sequence:")
    target_string = [int(i) for i in input().strip().split()]
    # Call the function
    table, wrapping = find_DTW(source_string, target_string)
    
    #print table
    print(np.array(table))
    #print the wrapping
    for move, value in wrapping:
        print("Move {}".format( value))

Enter the source sequence:
Enter the target sequence:
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  7  4  4  0  8  3  5  4]
 [ 0  6  5  2  4  6  6  2  5  4  6]
 [ 0  3  5  6  3  4  7  7  2  4  5]
 [ 0  7  9  5  6  6 11  8  6  4  7]
 [ 0  1  1  7  8  9  7 14  8  8  7]
 [ 0  8  8  2  6 10 15  7 12 11 11]
 [ 0  5  9  4  3  4  9 10  9  9 10]
 [ 0  4  7  7  3  3  7 11 10 10  9]
 [ 0  1  1  7  6  6  4 11 12 14 12]
 [ 0  1  3  9 11 11  5 13 15 18 17]]
Move 1
Move 2
Move 3
Move 6
Move 7
Move 7
Move 9
Move 9
Move 9
Move 12
Move 17


In [ ]:
1 7 4 8 2 9 6 5 2 0
1 2 8 5 5 1 9 4 6 5